### ISSUE TITLE
CoreOS Install

### ISSUE THREAD

**Issue by ShadySQL** [ElasticBox/elastickube#11]
I would love to install this on CoreOS. All of my kubernetes clusters are on azure and the project uses CoreOS as its oficial distro up on Azure.

**Comment by onyxet** [comment]
Have you any problems with installation?

**Comment by osanjuan** [comment]
Hi @ShadySQL we are gonna give it a try.

**Comment by albertoarias** [comment]
@ShadySQL did you try executing the install command from the command console?

curl -s https://elastickube.com | bash

**Comment by ShadySQL** [comment]
Yes from CoreOS but it failed completely. Failed also with sudo access. Does it work for you guys?

**Comment by albertoarias** [comment]
@ShadySQL I pushed an update that should help with the installation. If you already tried to install it before make sure the old replication controllers are deleted first:

`kubectl --namespace=kube-system delete rc elastickube-server`
`kubectl --namespace=kube-system delete rc elastickube-mongo`

Then execute the following command:

`curl -s https://elastickube.com | bash -s -- -u http://kube-00:8080`

Also I sent a PR to fix an issue you opened on the azure install scripts on the kubernetes repo:
https://github.com/kubernetes/kubernetes/pull/23498

**Comment by ShadySQL** [comment]
Hi Alberto, 
This time the install at least was somewhat successful. However the install still fails. See the attached pic.
![screen shot 2016-03-26 at 7 02 22 pm](https://cloud.githubusercontent.com/assets/7299059/14061298/72b4ec9a-f385-11e5-9a7d-9cbb3af38d7c.png)

**Comment by ShadySQL** [comment]
ok after deleting the replication controllers a couple of times and trying to install a couple of times. It seems that the install is now successful with the command you provided Alberto. But at the end of the install it provides this URL: http://10.20.162.223

But then also it gives the error: 
bash: line 39: KUBERNETES_MASTER_URL: //kubernetes: syntax error: operand expected (error token is "//kubernetes")

Please see attached. I am not able to access the endpoint on kube-00

![screen shot 2016-03-26 at 7 10 34 pm](https://cloud.githubusercontent.com/assets/7299059/14061336/b20698c0-f386-11e5-8103-a6e460a1dbd4.png)

And if I try to go to the URL of the cloudservice....I get only this:

{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/resetMetrics",
    "/swagger-ui/",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]
}

My cloud service or rather my kube-00 URL is:
http://kube-c1736658e4999c.cloudapp.net:8080/

**Comment by ShadySQL** [comment]
and after I run:
kubectl get pods
kubectl get rc

none are running. I dont think this works at all even do it says it did.

**Comment by albertoarias** [comment]
@ShadySQL I removed the public address of your cluster from the comment. Anybody with access to the unsecured port can perform any operation on your cluster. I recommend that you block the 8080 port.

The resources of ElasticKube are under the kube-system namespace, you should be able to see them if you execute:

`kubectl --namespace=kube-system get rc`

The issue you saw seeing is a timeout that happens during the pull of the image. I will fix that soon.

If you dont VPN into the cluster network you cannot use the address of the LoadBalancer. I tested it by exposing the node that was running the replication controller instead of the kube-apiserver node and it was working. This is not good though, the best way I can think to configure public access to ElasticKube (like any other applicaiton running in the cluster) is creating a public load balancer in Azure that sends the traffic to that particular node or nodes that might be running the replication controller. I will check out later how to do that.

**Comment by ShadySQL** [comment]
thanks for that. you said you:
 I tested it by exposing the node that was running the replication controller instead of the kube-apiserver node and it was working.

Well how did you do that? I am not able to even access it by:

http://publicdns:8080/api/v1/proxy/namespaces/kube-system/services/elastickube-server/

All I get is a blank page always

**Comment by albertoarias** [comment]
The project only works if it is running on the root path of the URL, this is due to some trickiness with the websocket URL.

@paulino-corujo @manolakis do you think we can make it work using relative urls?

http://<kuberenets_address>:8080/api/v1/proxy/namespaces/kube-system/services/elastickube-serve

**Comment by albertoarias** [comment]
@ShadySQL During my test what I changed this file to expose elastickube instead of the guestbook
https://github.com/albertoarias/kubernetes/blob/master/docs/getting-started-guides/coreos/azure/expose_guestbook_app_port.sh

I think this script need to be rewritten to create an additional VIPs on the LoadBalancer so more than app can be exposed.

**Comment by albertoarias** [comment]
@ShadySQL We just pushed some changes to the code that makes it possible to access elastickube through the kube-apiserver proxy (relative urls)

Please redeploy the elastickube-sever rc by deleting and executing the curl elastickube.com again with the -u parameter

`kubectl --namespace=kube-system delete rc elastickube-server`
`curl -s https://elastickube.com | bash -s -- -u http://kube-00:8080`

Also I found a way to access the cluster without having to open the port using a reverse ssh tunnel:
ssh -F  ./output/kube_<your_deployment_id>_ssh_conf kube-00 -L 9000:localhost:8080

And then open this url in the browser:
`localhost:9000/api/v1/proxy/namespaces/kube-system/services/elastickube-server`

**Comment by ShadySQL** [comment]
This seems to work but the problem is that it doesnt redirect me to the sign up page. Rather it directs me to the login page. 
![screen shot 2016-03-30 at 5 06 19 pm](https://cloud.githubusercontent.com/assets/7299059/14144801/f076ef22-f699-11e5-9532-dba08c398cf9.png)

**Comment by ShadySQL** [comment]
This is true also if I go to:

http://localhost:9000/api/v1/proxy/namespaces/kube-system/services/elastickube-server/signup

I get redirected to login:

http://localhost:9000/api/v1/proxy/namespaces/kube-system/services/elastickube-server/login

**Comment by paulino-corujo** [comment]
@ShadySQL Seems that there is an admin user already in the system. Did you create it?

**Comment by ShadySQL** [comment]
@paulino-corujo no I didnt. On the first go I tried to sign up and it gave me a metadata error. I refreshed the page and nothing. So I went back to kube-00 and deleted it by:

kubectl --namespace=kube-system delete rc elastickube-server
curl -s https://elastickube.com | bash -s -- -u http://kube-00:8080

And then created the SSH tunnel again. No success

**Comment by albertoarias** [comment]
@ShadySQL We managed to repro it.

The problem is that unless you pass the `-u http://kube-00:8080` parameter to the install script as per above every time you invoke it, there is no way for elastickube to contact the kubernetes api. The solution is to recreate the replication controllers with the parameter:

`kubectl --namespace=kube-system delete rc elastickube-server`
`curl -s https://elastickube.com | bash -s -- -u http://kube-00:8080`

We are doing a commit to handle the error better, but also we will be adding a diagnostics page that will make it a lot easier do detect what is wrong with the configuration. Check it out:
![image](https://cloud.githubusercontent.com/assets/658199/14150847/ee987728-f65f-11e5-93f8-9d4af0cc9836.png)

**Comment by ShadySQL** [comment]
I did that. I just ran the commands as above:

kubectl --namespace=kube-system delete rc elastickube-server
curl -s https://elastickube.com | bash -s -- -u http://kube-00:8080

and nothing. It gives me the login URL even though I specify the signup

**Comment by ShadySQL** [comment]
I am try to redeploy a new Kubernetes cluster to see if that would help out better.

**Comment by albertoarias** [comment]
@ShadySQL The reason is sending you to the signup is because the user was created even though the connection to kubernetes cannot be done. The first time you created the user it gave you an error but it actually created it, so now it asking you to login. I created my test cluster using the scripts from the kuberenetes repo, are you using the same scripts?

If it does not work can you send me the output of this command:
`kubectl --namespace=kube-system logs $(kubectl --namespace=kube-system get pod | grep elastickube-server | cut -f 1 -d " ") -c elastickube-api`

**Comment by ShadySQL** [comment]
I' am redeploying a kubernetes cluster. I follow this guide religiously: 
http://kubernetes.io/docs/getting-started-guides/coreos/azure/

**Comment by albertoarias** [comment]
@ShadySQL Don't forget to specify the subscription, they have not merged my PR yet with the fix to default the first subscription when is not specified ;-)

**Comment by albertoarias** [comment]
@ShadySQL Did you manage to get it up an running?

**Comment by ShadySQL** [comment]
Hey @albertoarias sorry for the late reply. Yes I got it work finally. Thanks so much for your help and I really appreciate what you guys are doing for the Kubernetes community. I saw your presentation at the google kubernetes community meetup - nice presentation by the way.
