### ISSUE TITLE
kubernetes endpoint seems to have moved to default in gke's deployment of k8s

### ISSUE THREAD

**Issue by mdbishop** [ElasticBox/elastickube#19]
As of v1.2 of K8S on Google's Container Engine, it appears that the kubernetes endpoint that ElasticBox looks for has moved to the default namespace:

```bash
TKE:~ mbishop$ kubectl describe ep kubernetes
Name:		kubernetes
Namespace:	default
Labels:		<none>
Subsets:
  Addresses:		xxx.xxx.xxx.xxx
  NotReadyAddresses:	<none>
  Ports:
    Name	Port	Protocol
    ----	----	--------
    https	443	TCP

No events.
```

Launching the install by using the endpoint above:
```bash
curl -s https://elastickube.com | bash -s -- -r -u https://xxx.xxx.xxx.xxx
```

Gives the desired effect, although it directs you to a cluster local IP for management rather than a public endpoint, which is fine:

```bash
  _____ _           _   _      _  __     _
 | ____| | __ _ ___| |_(_) ___| |/ /   _| |__   ___
 |  _| | |/ _` / __| __| |/ __| ' / | | | '_ \ / _ \
 | |___| | (_| \__ \ |_| | (__| . \ |_| | |_) |  __/
 |_____|_|\__,_|___/\__|_|\___|_|\_\__,_|_.__/ \___| by ElasticBox

Checking kubectl is available           [ ✓ ]
Verifying Kubernetes cluster            [ ✓ ]
Setting up elastickube-mongo            [ ✓ ]
Setting up elastickube-mongo svc        [ ✓ ]
Setting up elastickube-server           [ ✓ ]
Setting up elastickube-server svc       [ ✓ ]
Waiting for LB to be ready              [ ✓ ]

ElasticKube has been deployed!

Please complete the installation here: http://10.11.253.200

Name:                   elastickube-server
Namespace:              kube-system
Labels:                 name=elastickube-server
Selector:               name=elastickube-server
Type:                   LoadBalancer
IP:                     10.11.253.200
LoadBalancer Ingress:   xxx.xxx.xxx.xxx
Port:                   <unset> 80/TCP
NodePort:               <unset> 30109/TCP
Endpoints:              10.8.2.4:80
Session Affinity:       None
```

Perhaps a search of both default and kube-system and/or any other well known namespaces (ala Azure) would make startup a bit more robust?

**Comment by arnaud-elasticbox** [comment]
@mdbishop we have fixed the issue into https://github.com/ElasticBox/elastickube/pull/24, so you don't need to pass the address anymore as a parameter when deploying on GKE.

In addition, we have updated the deploy script to grep the Public IP of the Load balancer if available into #25

**Comment by mdbishop** [comment]
@arnaud-elasticbox 

Looks like #24 is all sorted, thanks!   At least for me, I'm still getting the cluster local IP so unfortunately #25 seems to still need a little tweaking.  If I can help troubleshoot, please just let me know.

**Comment by arnaud-elasticbox** [comment]
@mdbishop yes, it is possible. We are working on a more robust way to detect the IP address. The Public IP is not available immediately, so if the deployment completes before the IP becomes available, it will still show the local IP. Thanks for the feedback.
